### ISSUE TITLE
Install official Bitergia Analytics Plugin

### ISSUE THREAD

**Issue by sduenas** [Bitergia/bitergia-analytics-odfe-kibana#2]
The [current version of the Dockerfile](https://github.com/Bitergia/bitergia-analytics-odfe-kibana/blob/master/Dockerfile#L7) doesn't install the official version of the Bitergia Analytics Plugin. It takes it from the old repository.

It should point to: https://github.com/Bitergia/bitergia-analytics-plugin/releases/download/0.0.1_7.10.0/bitergiaAnalytics-7.10.0.zip

**Comment by dlumbrer** [comment]
Hi @sduenas, I submitted the PR of the fix (#4 )
