### ISSUE TITLE
Add missing plugin visualization components

### ISSUE THREAD

**Issue by sduenas** [Bitergia/bitergia-analytics-odfe-kibana#3]
There are some components that are missing that were available on the old kibiter image. These components are:

- [kbn_network](https://github.com/dlumbrer/kbn_network)
- [kbn_polar](https://github.com/dlumbrer/kbn_polar)
- [kbn_radar](https://github.com/dlumbrer/kbn_radar)

**Comment by dlumbrer** [comment]
Hi @sduenas ,

Finally, I migrated the plugins to the current Kibana version.

I added the [kbn_dotplot](https://github.com/dlumbrer/kbn_dotplot) plugin, it was missing in the list.

I submitted the PR, check it when you have time
